@startuml

title ERO REMOTE COMPONENT DIAGRAM

component "ERO_Remote.h" as ero_h
component "COM.h" as com_h
component "BLE.h" as ble_h
component "NAV.h" as nav_h
component "PERIPHERAL.h" as peri_h
component "MODE.h" as mode_h

@enduml